# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/release.yml in jtprogru/jlic
# from .github/templates/jlic.rb.tpl. Do not edit by hand.
class Jlic < Formula
  desc "Generate LICENSE files for open source projects"
  homepage "https://github.com/jtprogru/jlic"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/jlic/releases/download/v${VERSION}/jlic-v${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_AARCH64_DARWIN}"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v${VERSION}/jlic-v${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_X86_64_DARWIN}"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/jlic/releases/download/v${VERSION}/jlic-v${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_AARCH64_LINUX}"
    else
      url "https://github.com/jtprogru/jlic/releases/download/v${VERSION}/jlic-v${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_X86_64_LINUX}"
    end
  end

  def install
    bin.install "jlic"
    man1.install "man/jlic.1" if File.exist?("man/jlic.1")
    if File.directory?("completions")
      bash_completion.install "completions/jlic.bash" => "jlic"
      zsh_completion.install "completions/jlic.zsh" => "_jlic"
      fish_completion.install "completions/jlic.fish"
    end
  end

  test do
    system "#{bin}/jlic", "--version"
    system "#{bin}/jlic", "mit", "--stdout", "--name", "Test"
  end
end
